# Generated by Django 6.1.2 on 2026-10-09 17:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Nombre o número de la cama, ej: Cama 1, Cucheta 1-Alta', max_length=50)),
                ('bed_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('MATRIMONIAL', 'Matrimonial'), ('BUNK_TOP', 'Cucheta Alta'), ('BUNK_BOTTOM', 'Cucheta Baja')], default='INDIVIDUAL', max_length=20)),
                ('physical_status', models.CharField(choices=[('CLEAN', 'Limpia'), ('DIRTY', 'Sucia'), ('CLEANING', 'En Limpieza'), ('MAINTENANCE', 'Mantenimiento')], default='CLEAN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], default='DNI', max_length=20)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('nationality', models.CharField(default='Argentina', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número de habitación, ej: 101, 301', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('DOUBLE_PRIVATE', 'Doble Privada'), ('TRIPLE_PRIVATE', 'Triple'), ('SHARED_DORM', 'Compartida (6 plazas)')], max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Capacidad total de plazas/huéspedes')),
                ('floor', models.PositiveIntegerField(default=1)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('physical_status', models.CharField(choices=[('CLEAN', 'Limpia'), ('DIRTY', 'Sucia'), ('CLEANING', 'En Limpieza'), ('MAINTENANCE', 'Mantenimiento')], default='CLEAN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador / Gerente'), ('RECEPCION', 'Recepción'), ('LIMPIEZA', 'Personal de Limpieza')], default='RECEPCION', help_text='Rol en el sistema para control de acceso RBAC', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Alta / Creación'), ('UPDATE', 'Modificación'), ('CANCEL', 'Cancelación'), ('STATUS_CHANGE', 'Cambio de Estado Físico'), ('CHECK_IN', 'Check-in'), ('CHECK_OUT', 'Check-out'), ('MAINTENANCE', 'Mantenimiento'), ('AUTH', 'Autenticación / Seguridad')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDIENTE_SENA', 'Pendiente de Seña'), ('CONFIRMADA', 'Confirmada'), ('CHECK_IN', 'Check-in Realizado'), ('CHECK_OUT', 'Check-out Realizado'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_SENA', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beds', models.ManyToManyField(related_name='reservations', to='pms.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='pms.guest')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pms.room')),
            ],
            options={
                'ordering': ['-check_in_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_blocks', to='pms.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_blocks', to='pms.room')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='pms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'number')},
        ),
    ]
